"""Add Track T and Governance

Revision ID: 144051d65994
Revises: 44d10cdae2ce
Create Date: 2026-07-17 01:33:59.498910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144051d65994'
down_revision: Union[str, Sequence[str], None] = '44d10cdae2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_jobs', sa.Integer(), nullable=True),
    sa.Column('completed_jobs', sa.Integer(), nullable=True),
    sa.Column('failed_jobs', sa.Integer(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.add_column('runs', sa.Column('experiment_id', sa.String(), nullable=True))
    op.add_column('runs', sa.Column('raw_answer', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('policy_decision', sa.String(), nullable=True))
    op.add_column('runs', sa.Column('final_presented_answer', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('abstention_reason', sa.Text(), nullable=True))
    op.add_column('runs', sa.Column('certificate_id', sa.String(), nullable=True))
    op.add_column('runs', sa.Column('certificate_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'certificate_hash')
    op.drop_column('runs', 'certificate_id')
    op.drop_column('runs', 'abstention_reason')
    op.drop_column('runs', 'final_presented_answer')
    op.drop_column('runs', 'policy_decision')
    op.drop_column('runs', 'raw_answer')
    op.drop_column('runs', 'experiment_id')
    op.drop_table('experiments')
    # ### end Alembic commands ###
