"""Initial schema

Revision ID: 44d10cdae2ce
Revises: 
Create Date: 2026-07-14 22:42:36.106617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d10cdae2ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('world_id', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('natural_language_question', sa.Text(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('spec_json', sa.Text(), nullable=False),
    sa.Column('gold_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('gold_answer_value', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config_hash', sa.String(), nullable=True),
    sa.Column('artifact_refs_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('trace_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('parent_event_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('record_count_in', sa.Integer(), nullable=True),
    sa.Column('record_count_out', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('worlds',
    sa.Column('world_id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('scale_n', sa.Integer(), nullable=False),
    sa.Column('parent_world_id', sa.String(), nullable=True),
    sa.Column('creation_policy', sa.String(), nullable=True),
    sa.Column('record_ids_hash', sa.String(), nullable=False),
    sa.Column('manifest_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('world_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worlds')
    op.drop_table('trace_events')
    op.drop_table('runs')
    op.drop_table('queries')
    # ### end Alembic commands ###
